Repository kmayer10/ubs-devops, pull requests merged in 2019-08, with the labels that each got.

#5 New feature
  ayush.txt
  newfile.txt
  training.txt
Labels: bug

#6 Vasu mhashakhetri
  check.txt
  training.txt
Labels: enhancement

#9 Fix Table Pull
  .gitignore
  jai.md
Labels: documentation

#10 Ayush merge
  deepak.txt
  welcome.txt
Labels: bug
